### ISSUE TITLE
...........

### ISSUE THREAD

**Issue by Deepakofficials11** [kh4sh3i/Ransomware-Samples#2]
.

**Comment by pOlarcd** [comment]
Bruh, you can't. That's the point of ransomware.

**Comment by SantiagoCalebe** [comment]
Now, you cry

**Comment by Vitalik-Hakim** [comment]
This is the funniest issue I've seen on GitHub😂😂😂

**Comment by SantiagoCalebe** [comment]
> This is the funniest issue I've seen on GitHub😂😂😂

Same lol
